public enum FacebookEvent
{
	LOGIN_ATTEMPT,
	LOGIN_CANCELLED,
	LOGIN_FAILED,
	LOGIN,
	MY_DATA,
	FRIEND_DATA,
	NEW_FRIENDS_FETCHED,
	ALL_REQUESTS,
	ADD_FRIEND_REQUEST_ERROR,
	APP_REQUEST_RESULT,
	FRIEND_REQUEST_RESULT
}
