public enum PlayFabError
{
	NOT_AUTHENTICATED,
	ACCOUNT_NOT_LINKED,
	ACCOUNT_ALREADY_LINKED,
	LINKED_ACCOUNT_ALREADY_CLAIMED,
	ACCOUNT_NOT_FOUND,
	NICKNAME_NOT_AVAILABLE,
	PROFANE_DISPLAY_NAME,
	INSUFFICIENT_FUNDS,
	UNKNOWN
}
